// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_private_middleware from "./routes/(private)/_middleware.ts";
import * as $_private_cuenta from "./routes/(private)/cuenta.tsx";
import * as $_private_inicio from "./routes/(private)/inicio.tsx";
import * as $_private_paquete_paquete_despliegue from "./routes/(private)/paquete/[paquete]/despliegue.tsx";
import * as $_private_paquetes from "./routes/(private)/paquetes.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_private_cuenta_datosBasicos from "./routes/api/private/cuenta/datosBasicos.ts";
import * as $api_private_cuenta_listadoPaquetes from "./routes/api/private/cuenta/listadoPaquetes.ts";
import * as $api_private_cuenta_subirFotoPerfil from "./routes/api/private/cuenta/subirFotoPerfil.ts";
import * as $api_private_paquete_ingresarPaquete from "./routes/api/private/paquete/ingresarPaquete.ts";
import * as $api_private_paquete_listadoRecursos from "./routes/api/private/paquete/listadoRecursos.ts";
import * as $api_private_paquete_servicioDespliegueSubir from "./routes/api/private/paquete/servicioDespliegueSubir.ts";
import * as $api_recursos_despliegue_action from "./routes/api/recursos/despliegue/action.ts";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_registrarse from "./routes/auth/registrarse.tsx";
import * as $index from "./routes/index.tsx";
import * as $CabeceraPlataforma from "./islands/CabeceraPlataforma.tsx";
import * as $MaterialIcon from "./islands/MaterialIcon.tsx";
import * as $MaterialIconFilled from "./islands/MaterialIconFilled.tsx";
import * as $NavRailPrincipal from "./islands/NavRailPrincipal.tsx";
import * as $auth_FormularioLogin from "./islands/auth/FormularioLogin.tsx";
import * as $auth_FormularioRegistro from "./islands/auth/FormularioRegistro.tsx";
import * as $cuenta_informacionUsuario from "./islands/cuenta/informacionUsuario.tsx";
import * as $paquetes_ListadoPaquetes from "./islands/paquetes/ListadoPaquetes.tsx";
import * as $paquetes_PanelPaquete from "./islands/paquetes/PanelPaquete.tsx";
import * as $recursos_ListadoRecursos from "./islands/recursos/ListadoRecursos.tsx";
import * as $recursos_menuDespliegueTemporal from "./islands/recursos/menuDespliegueTemporal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(private)/_middleware.ts": $_private_middleware,
    "./routes/(private)/cuenta.tsx": $_private_cuenta,
    "./routes/(private)/inicio.tsx": $_private_inicio,
    "./routes/(private)/paquete/[paquete]/despliegue.tsx":
      $_private_paquete_paquete_despliegue,
    "./routes/(private)/paquetes.tsx": $_private_paquetes,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/private/cuenta/datosBasicos.ts":
      $api_private_cuenta_datosBasicos,
    "./routes/api/private/cuenta/listadoPaquetes.ts":
      $api_private_cuenta_listadoPaquetes,
    "./routes/api/private/cuenta/subirFotoPerfil.ts":
      $api_private_cuenta_subirFotoPerfil,
    "./routes/api/private/paquete/ingresarPaquete.ts":
      $api_private_paquete_ingresarPaquete,
    "./routes/api/private/paquete/listadoRecursos.ts":
      $api_private_paquete_listadoRecursos,
    "./routes/api/private/paquete/servicioDespliegueSubir.ts":
      $api_private_paquete_servicioDespliegueSubir,
    "./routes/api/recursos/despliegue/action.ts":
      $api_recursos_despliegue_action,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/registrarse.tsx": $auth_registrarse,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CabeceraPlataforma.tsx": $CabeceraPlataforma,
    "./islands/MaterialIcon.tsx": $MaterialIcon,
    "./islands/MaterialIconFilled.tsx": $MaterialIconFilled,
    "./islands/NavRailPrincipal.tsx": $NavRailPrincipal,
    "./islands/auth/FormularioLogin.tsx": $auth_FormularioLogin,
    "./islands/auth/FormularioRegistro.tsx": $auth_FormularioRegistro,
    "./islands/cuenta/informacionUsuario.tsx": $cuenta_informacionUsuario,
    "./islands/paquetes/ListadoPaquetes.tsx": $paquetes_ListadoPaquetes,
    "./islands/paquetes/PanelPaquete.tsx": $paquetes_PanelPaquete,
    "./islands/recursos/ListadoRecursos.tsx": $recursos_ListadoRecursos,
    "./islands/recursos/menuDespliegueTemporal.tsx":
      $recursos_menuDespliegueTemporal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
